version: "3.9"

secrets:
  JENKINS_ADMIN_ID:
   file: /home/docker/secrets/jenkins_admin_id.txt
  JENKINS_ADMIN_PASSWORD:
   file: /home/docker/secrets/jenkins_admin_password.txt

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'jenkins:jcasc'
    restart: unless-stopped
      #ports:
      #- '8080:8080'
      #- '50000:50000'
    networks:
      nginx-proxy-manager:
        ipv4_address: 172.16.220.30
        ipv6_address: 2001:3984:3989::30
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      CASC_JENKINS_CONFIG: /var/jenkins_home/jcasc.yaml
      JAVA_OPTS: -Djava.util.logging.config.file=/var/jenkins_home/log.properties
      JENKINS_ADMIN_ID: /run/secrets/JENKINS_ADMIN_ID
      JENKINS_ADMIN_PASSWORD: /run/secrets/JENKINS_ADMIN_PASSWORD
    volumes:
      - /home/docker/jenkins_home:/var/jenkins_home
      - /home/docker/jenkins_home/jcasc.yaml:/var/jenkins_home/jcasc.yaml
      - /home/docker/jenkins_home/log.properties:/var/jenkins_home/log.properties
    secrets:
      - JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD
    user: 1001:1001

networks:
  nginx-proxy-manager:
    external: true


