version: "3.9"
secrets:
  NGINX_DB_ROOT_PWD:
   file: /home/docker/secrets/nginx_db_root_pwd.txt
  NGINX_MYSQL_PWD:
    file: /home/docker/secrets/nginx_mysql_pwd.txt

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      nginx-pm:
        ipv4_address: 172.16.220.11
        ipv6_address: 2001:3984:3989::11
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "docker"
      DB_MYSQL_PASSWORD__FILE: /run/secrets/NGINX_MYSQL_PWD
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/docker/nginxpm/nginxpm:/data
      - /home/docker/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    secrets:
      - NGINX_MYSQL_PWD
    depends_on:
      - db

  db:
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/NGINX_DB_ROOT_PWD
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD_FILE: /run/secrets/NGINX_MYSQL_PWD
    networks:
      nginx-pm:
        ipv4_address: 172.16.220.12
        ipv6_address: 2001:3984:3989::12
    volumes:
      - /home/docker/nginxpm/nginxpm-db:/var/lib/mysql
    user: 1001:1001
    secrets:
      - NGINX_DB_ROOT_PWD
      - NGINX_MYSQL_PWD

networks:
  nginx-pm:
    name: nginx-proxy-manager
    ipam:
      driver: default
      config:
        - subnet: "172.16.220.0/24"
        - subnet: "2001:3984:3989::/64"

